//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ofiso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Offices()
        {
            this.Rentals = new HashSet<Rentals>();
        }
    
        public int ID { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public string Title { get; set; }
        public string Address { get; set; }
        public Nullable<int> Floor { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> PricePerMont { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rentals> Rentals { get; set; }
    }
}
