//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ofiso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rentals
    {
        public int ID { get; set; }
        public Nullable<int> OfficeID { get; set; }
        public Nullable<int> TenantID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Status { get; set; }
    
        public virtual Offices Offices { get; set; }
        public virtual Users Users { get; set; }
    }
}
